/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as CreativityRouteImport } from './routes/creativity'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as WriteRouteImport } from './routes/write'
import { Route as EditIdRouteImport } from './routes/edit.$id'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativityRoute = CreativityRouteImport.update({
  id: '/creativity',
  path: '/creativity',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/creativity': typeof CreativityRoute
  '/ideas': typeof IdeasRoute
  '/journeys': typeof JourneysRoute
  '/learning': typeof LearningRoute
  '/search': typeof SearchRoute
  '/stories': typeof StoriesRoute
  '/write': typeof WriteRoute
  '/edit/$id': typeof EditIdRoute
  '/post/$slug': typeof PostSlugRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/creativity': typeof CreativityRoute
  '/ideas': typeof IdeasRoute
  '/journeys': typeof JourneysRoute
  '/learning': typeof LearningRoute
  '/search': typeof SearchRoute
  '/stories': typeof StoriesRoute
  '/write': typeof WriteRoute
  '/edit/$id': typeof EditIdRoute
  '/post/$slug': typeof PostSlugRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/creativity': typeof CreativityRoute
  '/ideas': typeof IdeasRoute
  '/journeys': typeof JourneysRoute
  '/learning': typeof LearningRoute
  '/search': typeof SearchRoute
  '/stories': typeof StoriesRoute
  '/write': typeof WriteRoute
  '/edit/$id': typeof EditIdRoute
  '/post/$slug': typeof PostSlugRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/creativity'
    | '/ideas'
    | '/journeys'
    | '/learning'
    | '/search'
    | '/stories'
    | '/write'
    | '/edit/$id'
    | '/post/$slug'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/creativity'
    | '/ideas'
    | '/journeys'
    | '/learning'
    | '/search'
    | '/stories'
    | '/write'
    | '/edit/$id'
    | '/post/$slug'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/creativity'
    | '/ideas'
    | '/journeys'
    | '/learning'
    | '/search'
    | '/stories'
    | '/write'
    | '/edit/$id'
    | '/post/$slug'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  CreativityRoute: typeof CreativityRoute
  IdeasRoute: typeof IdeasRoute
  JourneysRoute: typeof JourneysRoute
  LearningRoute: typeof LearningRoute
  SearchRoute: typeof SearchRoute
  StoriesRoute: typeof StoriesRoute
  WriteRoute: typeof WriteRoute
  EditIdRoute: typeof EditIdRoute
  PostSlugRoute: typeof PostSlugRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creativity': {
      id: '/creativity'
      path: '/creativity'
      fullPath: '/creativity'
      preLoaderRoute: typeof CreativityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  CreativityRoute: CreativityRoute,
  IdeasRoute: IdeasRoute,
  JourneysRoute: JourneysRoute,
  LearningRoute: LearningRoute,
  SearchRoute: SearchRoute,
  StoriesRoute: StoriesRoute,
  WriteRoute: WriteRoute,
  EditIdRoute: EditIdRoute,
  PostSlugRoute: PostSlugRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
